### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by hossammourad** [cangoektas/react-on-off#6]

**Comment by cangoektas** [comment]
Hey,

I created a couple of examples on codesandbox when I was working on this. But I didn't have time yet to create a dedicated website for this or set up storybook or something like that. Hope these will help you:

### Toggle, Alert, and Dropdown components with `OnOff`:
- https://codesandbox.io/s/215r13op3r

### Accordion component with `OnOffCollection`:
- https://codesandbox.io/s/wy74w31y3l
